"""``python -m services.module_registry <command>`` (or ``python -m gurucloud_kb.modreg``
from the gurucloud-kb wheel) — the deterministic tool surface the
module_registry automation drives from its prompt.

Commands
    scan            --root . [--fan-in 3] [--json]        candidates with exports + fan-in
    purity          --file path [--symbol name]           purity verdict
    schema                                                print the prescribed run-DB DDL
    replay          --corpus c.jsonl --candidate pkg.mod:fn [--old pkg.mod:fn]   corpus or differential replay
    fuzz            --old pkg.mod:fn --new pkg.mod:fn [--corpus c.jsonl] [--max-examples N]
    corpus-stats    --corpus c.jsonl [--min-records 20] [--min-distinct 5]     corpus gate (exit 1 below gate)
    corpus-to-test  --corpus c.jsonl --candidate pkg.mod:fn --out tests/.../test_x_equivalence.py
    ledger          [--uri-file ~/.automation_run_db_uri] <init|summary|open|close|sync-scan|pending|decide|
                    kb-ids|verify-kb-ids|pair-ensure|pair-move|pairs|group-ensure|group-attach|group-move|groups|
                    finding|watermark get|set|shadow-observe> …   FSM-validated ledger (groups = N originals → 1 target)

The ledger commands are the ONLY supported way to write the run DB: they
validate pair transitions and append the evidence row atomically.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any


# The dotted package this harness is imported as: ``services.module_registry``
# inside the gurucloudai repository, ``gurucloud_kb.modreg`` when installed from
# the gurucloud-kb wheel in a foreign repository. Generated tests and the CLI
# prog name follow it so the same source works in both places.
HARNESS_PACKAGE = __package__ or "services.module_registry"


def _cmd_scan(a: argparse.Namespace) -> int:
    from .scan import DEFAULT_FAN_IN_THRESHOLD, scan_repository

    cands = scan_repository(Path(a.root), fan_in_threshold=a.fan_in if a.fan_in is not None else DEFAULT_FAN_IN_THRESHOLD)
    if a.json:
        print(json.dumps([c.as_dict() for c in cands], indent=2))
    else:
        for c in cands:
            flag = "shared" if c.shared_path else "fan-in"
            more = ", …" if len(c.exports) > 6 else ""
            print(f"{c.fan_in:4d} {flag:7s} {c.language:10s} {c.path}  [{', '.join(c.exports[:6])}{more}]")
        print(f"# {len(cands)} candidates", file=sys.stderr)
    return 0


def _cmd_purity(a: argparse.Namespace) -> int:
    from .purity import classify_file

    print(json.dumps(classify_file(Path(a.file), a.symbol).as_dict(), indent=2))
    return 0


def _cmd_schema(a: argparse.Namespace) -> int:
    from .pairs import schema_sql

    print(schema_sql())
    return 0


def _cmd_replay(a: argparse.Namespace) -> int:
    from .replay import replay_corpus, replay_differential
    from .tracer import load_corpus, resolve_target

    corpus = load_corpus(Path(a.corpus))
    _, _, candidate = resolve_target(a.candidate)
    if a.old:
        _, _, old = resolve_target(a.old)
        report = replay_differential(old, candidate, corpus)
    else:
        report = replay_corpus(candidate, corpus)
    print(json.dumps(report.as_dict(), indent=2))
    return 0 if report.verdict == "pass" else 1


def _cmd_fuzz(a: argparse.Namespace) -> int:
    from .fuzz import differential_fuzz
    from .tracer import load_corpus, resolve_target

    _, _, old = resolve_target(a.old)
    _, _, new = resolve_target(a.new)
    corpus = load_corpus(Path(a.corpus)) if a.corpus else None
    report = differential_fuzz(old, new, corpus=corpus, max_examples=a.max_examples)
    print(json.dumps(report.as_dict(), indent=2))
    return 0 if report.verdict == "pass" else 1


def corpus_stats(corpus: list[Any], *, min_records: int, min_distinct: int) -> dict:
    comparable = [r for r in corpus if not r.hashed and not r.opaque]
    shapes = {(r.args, r.kwargs) for r in comparable}
    return {
        "records": len(corpus), "comparable": len(comparable), "distinct_inputs": len(shapes),
        "hashed": sum(1 for r in corpus if r.hashed), "opaque": sum(1 for r in corpus if r.opaque),
        "gate": len(comparable) >= min_records and len(shapes) >= min_distinct,
        "min_records": min_records, "min_distinct": min_distinct,
    }


def _cmd_corpus_stats(a: argparse.Namespace) -> int:
    from .tracer import load_corpus

    stats = corpus_stats(load_corpus(Path(a.corpus)), min_records=a.min_records, min_distinct=a.min_distinct)
    print(json.dumps(stats, indent=2))
    return 0 if stats["gate"] else 1


_TEST_TEMPLATE = (
    '"""Characterization test generated by `python -m {pkg} corpus-to-test`.\n'
    "\n"
    "Replays a recorded corpus of real calls against the canonical module and\n"
    "asserts byte-for-byte equivalence (the module_registry harness, replay.py).\n"
    "Pair: {dup} -> {candidate}. Regenerate rather than hand-edit.\n"
    '"""\n'
    "from pathlib import Path\n"
    "\n"
    "from {pkg}.replay import replay_corpus\n"
    "from {pkg}.tracer import load_corpus, resolve_target\n"
    "\n"
    'CORPUS = Path(__file__).with_name("{corpus_name}")\n'
    "\n"
    "\n"
    "def test_{name}_matches_recorded_corpus() -> None:\n"
    "    corpus = load_corpus(CORPUS)\n"
    '    _, _, candidate = resolve_target("{candidate}")\n'
    "    report = replay_corpus(candidate, corpus)\n"
    "    assert report.compared > 0, report.as_dict()\n"
    '    assert report.verdict == "pass", report.as_dict()\n'
)


def write_corpus_test(corpus: Path, candidate: str, out: Path, old: str | None = None) -> tuple[Path, Path]:
    out.parent.mkdir(parents=True, exist_ok=True)
    stem = out.stem[5:] if out.stem.startswith("test_") else out.stem
    corpus_dst = out.with_name(stem + ".jsonl")
    corpus_dst.write_bytes(Path(corpus).read_bytes())
    name = stem.replace("-", "_")
    out.write_text(_TEST_TEMPLATE.format(pkg=HARNESS_PACKAGE, dup=old or "?", candidate=candidate, corpus_name=corpus_dst.name, name=name), encoding="utf-8")
    return out, corpus_dst


def _cmd_corpus_to_test(a: argparse.Namespace) -> int:
    out, corpus_dst = write_corpus_test(Path(a.corpus), a.candidate, Path(a.out), a.old)
    print(json.dumps({"test": str(out), "corpus": str(corpus_dst)}))
    return 0


def git_blob_sha(data: bytes) -> str:
    """The sha git would assign the blob (`git hash-object`), without git."""
    h = hashlib.sha1()
    h.update(f"blob {len(data)}\0".encode("utf-8"))
    h.update(data)
    return h.hexdigest()


def _parse_symbol(spec: str) -> tuple[str, str]:
    if ":" not in spec:
        raise SystemExit(f"expected <path>:<symbol>, got {spec!r}")
    path, symbol = spec.rsplit(":", 1)
    return path, symbol


def run_ledger_action(ledger: Any, a: argparse.Namespace) -> dict:
    """Dispatch one ledger action against an open Ledger. Returns the JSON
    result (printed by the CLI; asserted by tests)."""
    action = a.action
    if action == "init":
        ledger.apply_schema()
        return {"ok": True, "action": "init"}
    if action == "summary":
        return ledger.summary()
    if action == "open":
        if not a.session:
            raise SystemExit("--session is required")
        row = ledger.open_run(a.session, a.mode, a.head_sha)
        return {"run_id": row.id, "resumed": row.resumed, "mode": row.mode}
    if action == "close":
        counts = json.loads(a.counts) if a.counts else {}
        pending_kb_ids = ledger.flag_pending_kb_ids(a.run_id)
        ledger.close_run(a.run_id, a.outcome or "ok", counts, a.notes)
        return {"ok": True, "run_id": a.run_id, "pending_kb_ids": pending_kb_ids}
    if action == "sync-scan":
        from .scan import DEFAULT_FAN_IN_THRESHOLD, scan_repository

        root = Path(a.root).resolve()
        threshold = a.fan_in if a.fan_in is not None else DEFAULT_FAN_IN_THRESHOLD
        cands = scan_repository(root, fan_in_threshold=threshold)
        new = 0
        for c in cands:
            sha = git_blob_sha((root / c.path).read_bytes())
            if ledger.upsert_crawl_item(a.run_id, path=c.path, language=c.language, blob_sha=sha, fan_in=c.fan_in, shared_path=c.shared_path, exports=c.exports):
                new += 1
        # never-decided pending rows that no longer qualify (threshold raised, file
        # dropped below it, or now excluded) are closed as not_a_module with the
        # reason recorded, so the backlog reflects the current scanner rules.
        pruned = ledger.prune_pending_non_candidates(a.run_id, {c.path for c in cands}, reason=f"not a scan candidate at sync-scan (fan-in threshold {threshold})")
        return {"candidates": len(cands), "new_pending": new, "pruned_pending": pruned, "summary": ledger.summary()}
    if action == "pending":
        return {"items": ledger.pending_items(a.limit)}
    if action == "decide":
        ledger.decide_crawl_item(a.run_id, a.path, a.status, purity=a.purity, kb_entry_id=a.kb_entry_id, duplicate_of=a.duplicate_of, reason=a.reason, kb_id_pending=a.kb_id_pending)
        return {"ok": True, "path": a.path, "status": a.status}
    if action == "kb-ids":
        return {"items": ledger.kb_id_rows()}
    if action == "verify-kb-ids":
        if not a.resolved_file:
            raise SystemExit("--resolved-file is required (JSON object {kb_entry_id: true|false} from get_kb_entry)")
        resolved = json.loads(Path(a.resolved_file).read_text(encoding="utf-8"))
        if not isinstance(resolved, dict) or not all(isinstance(v, bool) for v in resolved.values()):
            raise SystemExit("--resolved-file must hold a JSON object mapping kb_entry_id to true (found) or false (entry_not_found)")
        return ledger.verify_kb_ids(a.run_id, resolved)
    if action == "pair-ensure":
        dp, ds = _parse_symbol(a.dup)
        cp, cs = _parse_symbol(a.canon)
        pid = ledger.ensure_pair(a.run_id, duplicate_path=dp, duplicate_symbol=ds, canonical_path=cp, canonical_symbol=cs, purity=a.purity or "pure")
        if a.group_id is not None:
            ledger.attach_member(pid, a.group_id, route_symbol=a.route, corpus_path=a.corpus_path)
        return {"pair_id": pid, "state": ledger.pair_state(pid), "consolidation_id": a.group_id}
    if action == "group-ensure":
        tp, ts = _parse_symbol(a.target)
        cid = ledger.ensure_consolidation(a.run_id, target_path=tp, target_symbol=ts, kind=a.group_kind or "adopt_canonical", note=a.note)
        return {"consolidation_id": cid, "members": ledger.group_members(cid)}
    if action == "group-attach":
        ledger.attach_member(a.pair_id, a.group_id, route_symbol=a.route, corpus_path=a.corpus_path)
        return {"ok": True, "pair_id": a.pair_id, "consolidation_id": a.group_id}
    if action == "group-move":
        cols: dict[str, Any] = {}
        if a.pr_number is not None:
            cols["pr_number"] = a.pr_number
        if a.card_id:
            cols["card_id"] = a.card_id
        if a.soak_started_at:
            cols["soak_started_at"] = a.soak_started_at
        evidence = json.loads(a.evidence) if a.evidence else {}
        if a.evidence_file:
            evidence["report"] = json.loads(Path(a.evidence_file).read_text(encoding="utf-8"))
        ledger.group_move(a.run_id, a.group_id, a.to, evidence, **cols)
        return {"ok": True, "consolidation_id": a.group_id, "state": a.to}
    if action == "groups":
        states = [s.strip() for s in (a.state or "").split(",") if s.strip()]
        return {"groups": ledger.groups_in_state(*states)}
    if action == "pair-move":
        cols: dict[str, Any] = {}
        if a.pr_number is not None:
            cols["pr_number"] = a.pr_number
        if a.card_id:
            cols["card_id"] = a.card_id
        if a.corpus_size is not None:
            cols["corpus_size"] = a.corpus_size
        if a.soak_started_at:
            cols["soak_started_at"] = a.soak_started_at
        evidence = json.loads(a.evidence) if a.evidence else {}
        if a.evidence_file:
            evidence["report"] = json.loads(Path(a.evidence_file).read_text(encoding="utf-8"))
        ledger.transition_pair(a.run_id, a.pair_id, a.to, evidence, **cols)
        return {"ok": True, "pair_id": a.pair_id, "state": a.to}
    if action == "pairs":
        states = [s.strip() for s in (a.state or "").split(",") if s.strip()]
        return {"pairs": ledger.pairs_in_state(*states)}
    if action == "finding":
        fid = ledger.add_finding(a.run_id, a.kind, path=a.path, canonical_path=a.canonical_path, pair_id=a.pair_id, action=a.finding_action, card_id=a.card_id, pr_number=a.pr_number, note=a.note, carry_forward=a.carry_forward, detail=json.loads(a.detail) if a.detail else None)
        return {"finding_id": fid}
    if action == "watermark":
        if a.wm_action == "get":
            return {"key": a.key, "value": ledger.get_watermark(a.key)}
        if a.wm_action != "set" or a.value is None:
            raise SystemExit("usage: ledger watermark get <key> | set <key> <value>")
        ledger.set_watermark(a.key, a.value)
        return {"ok": True, "key": a.key}
    if action == "shadow-observe":
        oid = ledger.add_shadow_observation(a.pair_id, calls=a.calls, shadowed=a.shadowed, mismatched=a.mismatched, shadow_time_s=a.shadow_time_s, detail=json.loads(a.detail) if a.detail else None)
        return {"observation_id": oid}
    raise SystemExit(f"unknown ledger action {action}")  # pragma: no cover - argparse restricts choices


def _cmd_ledger(a: argparse.Namespace) -> int:
    from .pairs import Ledger

    uri = Path(a.uri_file).expanduser().read_text(encoding="utf-8").strip()
    ledger = Ledger.connect(uri)
    result = run_ledger_action(ledger, a)
    if a.action == "watermark" and a.wm_action == "get":
        print(result.get("value") or "")
    else:
        print(json.dumps(result, indent=2, default=str))
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog=f"python -m {HARNESS_PACKAGE}", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("scan"); s.add_argument("--root", default="."); s.add_argument("--fan-in", type=int, default=None); s.add_argument("--json", action="store_true"); s.set_defaults(fn=_cmd_scan)
    s = sub.add_parser("purity"); s.add_argument("--file", required=True); s.add_argument("--symbol"); s.set_defaults(fn=_cmd_purity)
    s = sub.add_parser("schema"); s.set_defaults(fn=_cmd_schema)
    s = sub.add_parser("replay"); s.add_argument("--corpus", required=True); s.add_argument("--candidate", required=True); s.add_argument("--old"); s.set_defaults(fn=_cmd_replay)
    s = sub.add_parser("fuzz"); s.add_argument("--old", required=True); s.add_argument("--new", required=True); s.add_argument("--corpus"); s.add_argument("--max-examples", type=int, default=500); s.set_defaults(fn=_cmd_fuzz)
    s = sub.add_parser("corpus-stats"); s.add_argument("--corpus", required=True); s.add_argument("--min-records", type=int, default=20); s.add_argument("--min-distinct", type=int, default=5); s.set_defaults(fn=_cmd_corpus_stats)
    s = sub.add_parser("corpus-to-test"); s.add_argument("--corpus", required=True); s.add_argument("--candidate", required=True); s.add_argument("--old"); s.add_argument("--out", required=True); s.set_defaults(fn=_cmd_corpus_to_test)

    s = sub.add_parser("ledger", help="run-DB ledger (FSM-validated)")
    s.add_argument("action", choices=["init", "summary", "open", "close", "sync-scan", "pending", "decide", "kb-ids", "verify-kb-ids", "pair-ensure", "pair-move", "pairs", "group-ensure", "group-attach", "group-move", "groups", "finding", "watermark", "shadow-observe"])
    s.add_argument("wm_action", nargs="?", choices=["get", "set"]); s.add_argument("key", nargs="?"); s.add_argument("value", nargs="?")
    s.add_argument("--uri-file", default=os.environ.get("MODULE_REGISTRY_RUN_DB_URI_FILE", "~/.automation_run_db_uri"), help="file holding the run-DB URI (never pass the URI itself on argv)")
    s.add_argument("--run-id", type=int); s.add_argument("--session"); s.add_argument("--mode", choices=["bootstrap", "incremental"], default="bootstrap"); s.add_argument("--head-sha")
    s.add_argument("--outcome"); s.add_argument("--counts"); s.add_argument("--notes")
    s.add_argument("--root", default="."); s.add_argument("--fan-in", type=int, default=None, help="fan-in threshold for non-shared paths (default scan.DEFAULT_FAN_IN_THRESHOLD)"); s.add_argument("--limit", type=int, default=20)
    s.add_argument("--path"); s.add_argument("--status"); s.add_argument("--purity"); s.add_argument("--kb-entry-id"); s.add_argument("--duplicate-of"); s.add_argument("--reason")
    s.add_argument("--kb-id-pending", action="store_true", help="decide: --kb-entry-id is a report_learning pending id not yet confirmed live")
    s.add_argument("--resolved-file", help="verify-kb-ids: JSON {kb_entry_id: true|false} from get_kb_entry")
    s.add_argument("--dup"); s.add_argument("--canon"); s.add_argument("--pair-id", type=int); s.add_argument("--to"); s.add_argument("--evidence"); s.add_argument("--evidence-file")
    s.add_argument("--target", help="group target <path>:<symbol> (the ONE new version)"); s.add_argument("--group-kind", choices=["adopt_canonical", "merged_version"]); s.add_argument("--group-id", type=int); s.add_argument("--route", help="<path>:<symbol> invoking the target in place of this original"); s.add_argument("--corpus-path")
    s.add_argument("--pr-number", type=int); s.add_argument("--card-id"); s.add_argument("--corpus-size", type=int); s.add_argument("--soak-started-at"); s.add_argument("--state", default="")
    s.add_argument("--kind"); s.add_argument("--canonical-path"); s.add_argument("--finding-action", "--action", dest="finding_action", help="finding: value for the action column (e.g. repoint)"); s.add_argument("--note"); s.add_argument("--carry-forward", action="store_true"); s.add_argument("--detail")
    s.add_argument("--calls", type=int, default=0); s.add_argument("--shadowed", type=int, default=0); s.add_argument("--mismatched", type=int, default=0); s.add_argument("--shadow-time-s", type=float, default=0.0)
    s.set_defaults(fn=_cmd_ledger)
    return p


def main(argv: list[str] | None = None) -> int:
    a = build_parser().parse_args(argv)
    return int(a.fn(a))


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
